### ISSUE TITLE
Unable to run moderator on aiohttp 3.8.3

### ISSUE THREAD

**Issue by likunshu** [aio-libs/aiohttp-demos#197]
Running the example moderator with `aiohttp=3.8.3` rise a error when POST:

```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/Users/kunshu/opt/anaconda3/envs/aio38/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/Users/kunshu/opt/anaconda3/envs/aio38/lib/python3.8/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/Users/Kunshu/Work/aiohttp-demos/demos/moderator/moderator/handlers.py", line 26, in moderate
    results = await run(self._executor, predict_probability, features)
RuntimeError: Task <Task pending name='Task-8' coro=<RequestHandler._handle_request() running at /Users/kunshu/opt/anaconda3/envs/aio38/lib/python3.8/site-packages/aiohttp/web_protocol.py:433> cb=[<TaskWakeupMethWrapper object at 0x103d47ca0>()]> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /Users/kunshu/opt/anaconda3/envs/aio38/lib/python3.8/asyncio/futures.py:360]> attached to a different loop
```

While I tried to use `aiohttp==3.7.4`, it worked without the error.

By the way, the model example used rises a `ModuleNotFoundError: No module named 'sklearn.linear_model.logistic'` error with `sciki-learn==1.1.2`. Downgrade to `scikit-learn==0.23.2` solves the problem.

**Comment by Dreamsorcerer** [comment]
Fixing the tests in #196 (if possible).
Issue with newer sklearn is in #188.
