### ISSUE TITLE
Graphql demo code throwing error

### ISSUE THREAD

**Issue by SaddamBInSyed** [aio-libs/aiohttp-demos#85]
Hi.

I have carefully followed the document instruction and when I execute the "sudo make prepare_database" command then I am getting the below error.

deeplearning@XXX: ~/Desktop/ML_Practise/aiohttp-demos/demos/graphql$ sudo make start_database 
Starting graphql_postgres_1 ... done
deeplearning@XXX: ~/Desktop/ML_Practise/aiohttp-demos/demos/graphql$ sudo make start_redis 
Starting graphql_redis_1 ... done
deeplearning@XXX: ~/Desktop/ML_Practise/aiohttp-demos/demos/graphql$ sudo make prepare_database 
Start to generate a new data...
Traceback (most recent call last):
  File "prepare_database.py", line 153, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "prepare_database.py", line 142, in main
    users = await generate_users(conn, 20)
  File "prepare_database.py", line 88, in generate_users
    return [user[0] for user in response]
TypeError: 'ResultProxy' object is not iterable
/usr/local/lib/python3.6/dist-packages/aiopg/pool.py:310: ResourceWarning: Unclosed 1 connections in <aiopg.pool.Pool object at 0x7f5b4ad8ac18>
Makefile:26: recipe for target 'prepare_database' failed
make: *** [prepare_database] Error 1

also when I execute the Make Run command I am getting below error.

deeplearning@XXX :~/Desktop/ML_Practise/aiohttp-demos/demos/graphql$ sudo make run
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/deeplearning/Desktop/ML_Practise/aiohttp-demos/demos/graphql/graph/__main__.py", line 3, in <module>
    from .app import init_app
  File "/home/deeplearning/Desktop/ML_Practise/aiohttp-demos/demos/graphql/graph/app.py", line 10, in <module>
    from graph.routes import init_routes
  File "/home/deeplearning/Desktop/ML_Practise/aiohttp-demos/demos/graphql/graph/routes.py", line 3, in <module>
    from graph.api.views import (
  File "/home/deeplearning/Desktop/ML_Practise/aiohttp-demos/demos/graphql/graph/api/views.py", line 3, in <module>
    import graphene
  File "/usr/local/lib/python3.6/dist-packages/graphene/__init__.py", line 3, in <module>
    from .types import (
  File "/usr/local/lib/python3.6/dist-packages/graphene/types/__init__.py", line 2, in <module>
    from graphql import ResolveInfo
ImportError: cannot import name 'ResolveInfo'
Makefile:8: recipe for target 'run' failed
make: *** [run] Error 1

please advise.

**Comment by Arfey** [comment]
Hi. Now we have a problem with the new version of graphene. We will fix this soon.

**Comment by Arfey** [comment]
https://github.com/aio-libs/aiohttp-demos/pull/95

**Comment by SaddamBInSyed** [comment]
@Arfey 
Thanks for your response.

waiting for the fix.

**Comment by Arfey** [comment]
Try to check

**Comment by SaddamBInSyed** [comment]
ok sure, I will check and update you.

thanks.
